site_name: Micro API Call Framework
name: test
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
      - python
markdown_extensions:
  - admonition
nav:
  - 'guide.md'
  - 'cli.md'
  - 'versions.md'
  - 'contributing.md'
  - 'FAQ.md'
